### ISSUE TITLE
Frege-repl-core with Frege version 3.22.524?

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-repl#24]
for the javafx repl I tried use frege-repl-core with frege version 3.22.524-gcc99d7e but got the error below.

Any plans to upgrade the frege version?

cheers
Dierk

Exception in thread "main" java.lang.NoSuchMethodError: frege.compiler.types.Global$TOptions.mk(Ljava/lang/String;Lfrege/prelude/PreludeBase$TList;JLjava/lang/String;Lfrege/prelude/PreludeBase$TList;Ljava/lang/String;Lfrege/prelude/PreludeBase$TMaybe;Lfrege/prelude/PreludeBase$TList;)Lfrege/compiler/types/Global$TOptions;
	at frege.interpreter.FregeInterpreter.createopts(FregeInterpreter.java:6830)
	at frege.interpreter.FregeInterpreter$26$1.eval(FregeInterpreter.java:6851)

**Comment by mmhelloworld** [comment]
`frege-repl` is now updated for `3.22.524` and the new version is deployed in Sonatype: https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-repl-core/1.2.1-SNAPSHOT/ .

**Comment by Dierk** [comment]
cool, thanks!
