### ISSUE TITLE
:t infixl crashes repl

### ISSUE THREAD

**Issue by vijaykiran** [Frege/frege-repl#26]
Here's the transcript:

```
➜  frege  fregerepl
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Welcome to Frege 3.21.586-g026e8d7 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM, 1.8.0_45)

frege> :t infixl 9 `!!`
Not an expression!

frege> :t infixl 9
[ERROR: 4]: unexpected token "infixl" while trying to parse a function or
pattern binding

frege> :t infixl foo
[ERROR: 4]: Illegal precedence `foo´, must be integer from range 1..16

frege> infixl foo
[ERROR: 4]: Illegal precedence `foo´, must be integer from range 1..16

frege> infixl 9 `!!`

frege> :t infixl
Exception in thread "main" frege.runtime.Undefined: tail []
	at frege.prelude.PreludeBase.error(PreludeBase.java:18445)
	at frege.prelude.PreludeList$IListView__lbrack_rbrack.tail(PreludeList.java:2332)
	at frege.compiler.Scanner$1Floop_28130.work(Scanner.java:3224)
	at frege.compiler.Scanner.findInfixImports(Scanner.java:3242)
	at frege.compiler.Scanner$33$1.eval(Scanner.java:3834)
	at frege.compiler.Scanner$33$1.eval(Scanner.java:3831)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.compiler.Scanner.processImports(Scanner.java:2837)
	at frege.compiler.Scanner$33.eval(Scanner.java:3840)
	at frege.compiler.Scanner$33.eval(Scanner.java:3823)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$11.eval(FregeInterpreter.java:5933)
	at frege.interpreter.FregeInterpreter$11.eval(FregeInterpreter.java:5864)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$7$1.eval(FregeInterpreter.java:5584)
	at frege.interpreter.FregeInterpreter$7$1.eval(FregeInterpreter.java:5579)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:200)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$24.eval(FregeInterpreter.java:7341)
	at frege.interpreter.FregeInterpreter$24.eval(FregeInterpreter.java:7298)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$1FcalcSourceType_5816.work(FregeInterpreter.java:7466)
	at frege.interpreter.FregeInterpreter.findSourceType(FregeInterpreter.java:7474)
	at frege.interpreter.FregeInterpreter$Ĳ$findSourceTypeƒ56008840.eval(FregeInterpreter.java:9091)
	at frege.interpreter.FregeInterpreter$Ĳ$findSourceTypeƒ56008840.eval(FregeInterpreter.java:9084)
	at frege.runtime.Fun2$2.eval(Fun2.java:77)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.interpreter.FregeInterpreter$Ĳ$buildScriptƒ5d0e5c8b.eval(FregeInterpreter.java:9134)
	at frege.interpreter.FregeInterpreter$Ĳ$buildScriptƒ5d0e5c8b.eval(FregeInterpreter.java:9127)
	at frege.runtime.Fun5$2.eval(Fun5.java:77)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.interpreter.FregeInterpreter$11$3.eval(FregeInterpreter.java:5929)
	at frege.interpreter.FregeInterpreter$11$3.eval(FregeInterpreter.java:5927)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.compiler.Scanner$Ĳ$lexƒ38588a19.eval(Scanner.java:4274)
	at frege.compiler.Scanner$Ĳ$lexƒ38588a19.eval(Scanner.java:4267)
	at frege.runtime.Fun4$2.eval(Fun4.java:77)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.prelude.PreludeList$Ĳ$filterƒe0a8f25.eval(PreludeList.java:3531)
	at frege.prelude.PreludeList$Ĳ$filterƒe0a8f25.eval(PreludeList.java:3524)
	at frege.runtime.Fun2$2.eval(Fun2.java:77)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.compiler.Scanner$Ĳ$layoutƒf631e324.eval(Scanner.java:4300)
	at frege.compiler.Scanner$Ĳ$layoutƒf631e324.eval(Scanner.java:4293)
	at frege.runtime.Fun2$2.eval(Fun2.java:77)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.compiler.Scanner$33$1.eval(Scanner.java:3834)
	at frege.compiler.Scanner$33$1.eval(Scanner.java:3831)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.compiler.Scanner.processImports(Scanner.java:2837)
	at frege.compiler.Scanner$33.eval(Scanner.java:3840)
	at frege.compiler.Scanner$33.eval(Scanner.java:3823)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$11.eval(FregeInterpreter.java:5933)
	at frege.interpreter.FregeInterpreter$11.eval(FregeInterpreter.java:5864)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$7$1.eval(FregeInterpreter.java:5584)
	at frege.interpreter.FregeInterpreter$7$1.eval(FregeInterpreter.java:5579)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:200)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.control.monad.State$IMonad_State$3.eval(State.java:1939)
	at frege.control.monad.State$IMonad_State$3.eval(State.java:1936)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$26.eval(FregeInterpreter.java:7550)
	at frege.interpreter.FregeInterpreter$26.eval(FregeInterpreter.java:7528)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$27$1.eval(FregeInterpreter.java:7669)
	at frege.interpreter.FregeInterpreter$27$1.eval(FregeInterpreter.java:7633)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$IMonad_Interpreter$3.eval(FregeInterpreter.java:4723)
	at frege.interpreter.FregeInterpreter$IMonad_Interpreter$3.eval(FregeInterpreter.java:4719)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.control.arrow.Kleisli$IMonad_Kleisli$1Fgo_23179$1.eval(Kleisli.java:1182)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.control.monad.State$IMonad_State$4.eval(State.java:1960)
	at frege.control.monad.State$IMonad_State$4.eval(State.java:1953)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:200)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.control.monad.State$IMonad_State$4.eval(State.java:1956)
	at frege.control.monad.State$IMonad_State$4.eval(State.java:1953)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.interpreter.FregeInterpreter$TInterpreter.run(FregeInterpreter.java:3965)
	at frege.repl.FregeRepl$21$1.eval(FregeRepl.java:5857)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.repl.FregeRepl$IMonad_Repl._return(FregeRepl.java:4515)
	at frege.repl.FregeRepl$21.eval(FregeRepl.java:5846)
	at frege.repl.FregeRepl$21.eval(FregeRepl.java:5844)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.repl.FregeRepl$IMonad_Repl$3.eval(FregeRepl.java:4477)
	at frege.repl.FregeRepl$IMonad_Repl$3.eval(FregeRepl.java:4468)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.repl.FregeRepl$TRepl.run(FregeRepl.java:3557)
	at frege.repl.FregeRepl$40.eval(FregeRepl.java:6619)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:200)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.repl.FregeRepl$41.eval(FregeRepl.java:6691)
	at frege.runtime.Fun1$1.eval(Fun1.java:62)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Runtime.runMain(Runtime.java:225)
	at frege.repl.FregeRepl.main(FregeRepl.java:7414)
➜  frege
```

**Comment by Ingo60** [comment]
Though your repl is very old, a similar error occurs with more recent parser and scanner and will be fixed.

Note that this is not a REPL issue, you get basically the same error from the compiler. The reason being that some token that was inserted by error recovery gets interpreted in a faulty way. This causes the whole thing to abort, before the syntax error message can be displayed.

**Comment by Ingo60** [comment]
Should be fixed by commit https://github.com/Frege/frege/commit/d535935036d5057796a27c40e79b579cf074b73c

**Comment by mmhelloworld** [comment]
Thanks Ingo! I am in the middle of upgrading REPL to use the latest Frege. Hopefully I will include this fix in the next release of REPL.
