### ISSUE TITLE
event expansion vs. tab expansion

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-repl#37]
It looks like the jline repl does "event expansion":

    frege> !true
    [ERROR] Could not expand event
    java.lang.IllegalArgumentException: !true: event not found
	at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:849)
	at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:700)
	at jline.console.ConsoleReader.accept(ConsoleReader.java:2010)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2691)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
        ....

This is unfortunate, as we have to escape every occurence of `!`  with a backslash.
Is it possible to turn this off?

On a related note, what would be great to have would be tab expansion.
I am sure there are some predefined tab-handlers that take a list of items or some such, and that list could easily be constructed from the base names of all known symbols, plus the known module names.

**Comment by mmhelloworld** [comment]
I have disabled event expansion so `!` should work now. I have updated the snapshot release with this fix.

Regarding tab expansion, jline does support the concept of `completers` so it should be possible to define one for Frege symbols. I will dig into this.
